INSERT INTO Users (username, email, password)
VALUES
('John Doe', 'john.doe@example.com', '123456'),
('Jane Doe', 'jane.doe@example.com', '123456'),
('Bob Smith', 'bob.smith@example.com', '123456'),
('Alice Johnson', 'alice.johnson@example.com', '123456'),
('David Lee', 'david.lee@example.com', '123456'),
('Linda Davis', 'linda.davis@example.com', '123456'),
('Michael Brown', 'michael.brown@example.com', '123456'),
('Emily Wilson', 'emily.wilson@example.com', '123456'),
('Jessica Green', 'jessica.green@example.com', '123456'),
('William Clark', 'william.clark@example.com', '123456');
INSERT INTO DialogList (user_id, dialog_name, dialog_avt, is_mark) VALUES
(1, 'Family Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(1).png', TRUE),
(2, 'Work Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(2).png', TRUE),
(3, 'Hobby Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(3).png', FALSE),
(1, 'Friends Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(4).png', FALSE),
(2, 'Project Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(5).png', FALSE),
(3, 'News Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(6).png', FALSE),
(1, 'Travel Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(7).png', FALSE),
(2, 'Study Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(8).png', FALSE),
(3, 'Sports Chat', 'https://aldortio.sirv.com/Sunrise%20Assistant/Assistants/assistant%20(9).png', FALSE);
INSERT INTO Dialogs (dialog_id, sender, msg) VALUES
(1, 'User', 'Xin chào! Tôi cần hỗ trợ về sản phẩm của bạn.'),
(1, 'Assistant', 'Xin chào! Tôi sẵn sàng hỗ trợ bạn. Bạn cần giúp gì ạ?'),
(1, 'User', 'Tôi đang xem sản phẩm ABC của bạn, tôi muốn biết thêm thông tin về sản phẩm này.'),
(1, 'Assistant', 'Được ạ, sản phẩm ABC của chúng tôi là sản phẩm chất lượng cao, được sản xuất từ các nguyên liệu tốt nhất.'),
(1, 'Assistant', 'Với sản phẩm này, bạn sẽ nhận được các tính năng đặc biệt như ...'),
(1, 'Assistant', 'Và giá cả cũng rất hợp lý với chất lượng của sản phẩm.'),
(1, 'User', 'Tôi cần biết thêm về các khuyến mãi đang có.'),
(1, 'Assistant', 'Hiện tại chúng tôi đang có chương trình khuyến mãi giảm giá cho sản phẩm ABC, với mỗi sản phẩm mua được giảm 10%.'),
(1, 'Assistant', 'Ngoài ra, chúng tôi còn có nhiều chương trình khuyến mãi khác như...'),
(1, 'User', 'Tôi cảm ơn bạn rất nhiều. Tôi sẽ xem xét và liên hệ lại nếu cần.'),
(1, 'Assistant', 'Không có gì, nếu bạn cần hỗ trợ thêm, hãy liên hệ với chúng tôi.'),
(1, 'Assistant', 'Chúc bạn một ngày tốt lành!'),
(2, 'User', 'Xin chào! Tôi cần giúp đỡ về dịch vụ của bạn.'),
(2, 'Assistant', 'Xin chào! Tôi có thể giúp gì cho bạn?'),
(2, 'User', 'Tôi muốn biết về các gói dịch vụ của bạn.'),
(2, 'Assistant', 'Chúng tôi hiện có 3 gói dịch vụ: Gói A, Gói B và Gói C. Bạn muốn tìm hiểu về gói nào?'),
(2, 'User', 'Tôi quan tâm đến Gói A.'),
(2, 'Assistant', 'Gói A cung cấp các tính năng sau: tính năng A1, tính năng A2, và tính năng A3. Gói này có giá là $50/tháng.'),
(2, 'User', 'Tôi cần biết thêm về tính năng A2.'),
(2, 'Assistant', 'Tính năng A2 cho phép bạn thực hiện việc XYZ. Bạn có muốn đăng ký Gói A không?'),
(2, 'User', 'Tôi cần suy nghĩ thêm.'),
(2, 'Assistant', 'Không vấn đề gì cả. Hãy liên hệ với chúng tôi nếu bạn cần thêm thông tin.'),
(2, 'User', 'Cảm ơn bạn nhiều!'),
(3, 'User', 'Xin chào! Tôi cần hỗ trợ về đặt hàng.'),
(3, 'Assistant', 'Xin chào! Tôi có thể giúp gì cho bạn?'),
(3, 'User', 'Tôi muốn đặt hàng sản phẩm A.'),
(3, 'Assistant', 'Để đặt hàng sản phẩm A, bạn cần truy cập trang sản phẩm và thực hiện các bước đặt hàng.'),
(3, 'User', 'Tôi không tìm thấy trang sản phẩm.'),
(3, 'Assistant', 'Vui lòng truy cập trang chủ của chúng tôi và tìm kiếm sản phẩm A. Nếu bạn gặp khó khăn, hãy liên hệ với chúng tôi để được hỗ trợ.'),
(3, 'User', 'Cảm ơn bạn.'),
(3, 'Assistant', 'Không có gì. Hãy liên hệ với chúng tôi nếu bạn cần thêm thông tin về sản phẩm A hoặc bất kỳ sản phẩm nào khác của chúng tôi.'),
(4, 'User', 'Xin chào, tôi muốn hỏi về dịch vụ của bạn.'),
(4, 'Assistant', 'Chào bạn, chúng tôi sẽ cố gắng hỗ trợ bạn tốt nhất có thể. Bạn muốn hỏi về dịch vụ gì ạ?'),
(4, 'User', 'Tôi muốn biết thêm về gói dịch vụ Basic của bạn.'),
(4, 'Assistant', 'Được ạ, gói dịch vụ Basic của chúng tôi là gói cơ bản nhất với các tính năng như ...'),
(4, 'Assistant', 'Nếu bạn cần thêm thông tin chi tiết hơn, tôi có thể gửi bảng giá và thông tin chi tiết cho bạn.'),
(4, 'User', 'Được ạ, tôi muốn nhận thông tin đó.'),
(4, 'Assistant', 'Vâng, tôi sẽ gửi thông tin đó cho bạn ngay bây giờ.'),
(5, 'User', 'Xin chào, tôi cần hỗ trợ về đơn hàng của mình.'),
(5, 'Assistant', 'Chào bạn, vui lòng cho mình biết mã đơn hàng của bạn để mình có thể tra cứu thông tin giúp bạn nhé.'),
(5, 'User', 'Mã đơn hàng của tôi là DH123456.'),
(5, 'Assistant', 'Được rồi, để mình kiểm tra thông tin đơn hàng của bạn. Vui lòng đợi một chút.'),
(5, 'Assistant', 'Đơn hàng của bạn là đơn hàng đang được vận chuyển. Nó sẽ đến địa chỉ của bạn vào ngày mai.'),
(5, 'User', 'Cảm ơn bạn rất nhiều về thông tin này.'),
(5, 'Assistant', 'Không có gì, nếu bạn cần hỗ trợ gì thêm, hãy liên hệ với chúng tôi.'),
(6, 'User', 'Xin chào, tôi muốn đăng ký thành viên của trang web.'),
(6, 'Assistant', 'Chào bạn, để đăng ký thành viên, bạn cần điền đầy đủ thông tin cá nhân và chọn tên đăng nhập và mật khẩu.'),
(6, 'Assistant', 'Bạn có thể truy cập trang đăng ký thành viên để thực hiện.'),
(7, 'User', 'Xin chào, tôi đang gặp vấn đề với đơn hàng của mình.'),
(7, 'Assistant', 'Chào bạn, chúng tôi rất tiếc vì sự cố này. Bạn vui lòng cung cấp thêm thông tin cho tôi để tôi có thể giúp bạn được không?'),
(7, 'User', 'Tôi đã đặt hàng trực tuyến nhưng đơn hàng của tôi bị hủy bỏ và tôi chưa được hoàn tiền.'),
(7, 'Assistant', 'Rất tiếc vì sự cố này. Bạn có thể cho tôi biết số đơn hàng của bạn để tôi có thể kiểm tra được không?'),
(7, 'User', 'Số đơn hàng của tôi là 123456789.'),
(7, 'Assistant', 'Cảm ơn bạn, tôi sẽ kiểm tra thông tin và liên lạc lại với bạn trong vòng 24 giờ.'),
(7, 'User', 'Cảm ơn bạn nhiều.'),
(8, 'User', 'Tôi muốn đặt hàng sản phẩm XYZ nhưng không biết cách thức đặt hàng.'),
(8, 'Assistant', 'Chào bạn, để đặt hàng sản phẩm XYZ của chúng tôi, bạn có thể truy cập trang web của chúng tôi và chọn sản phẩm mong muốn, sau đó đăng nhập và điền thông tin giao hàng và thanh toán.'),
(8, 'User', 'Cảm ơn bạn, tôi sẽ làm theo hướng dẫn của bạn.'),
(8, 'Assistant', 'Nếu bạn có bất kỳ câu hỏi nào trong quá trình đặt hàng, hãy liên hệ với chúng tôi để được hỗ trợ.'),
(9, 'User', 'Tôi muốn đổi trả sản phẩm vì không hài lòng với chất lượng sản phẩm.'),
(9, 'Assistant', 'Rất tiếc về sự bất tiện này. Bạn có thể cung cấp cho tôi số đơn hàng và lí do đổi trả được không?'),
(9, 'User', 'Số đơn hàng của tôi là 987654321 và tôi muốn đổi trả vì sản phẩm không đúng với mô tả trên trang web.'),
(9, 'Assistant', 'Cảm ơn bạn đã cung cấp thông tin. Chúng tôi sẽ tiến hành kiểm tra và liên lạc lại với bạn trong vòng 24 giờ để giải quyết vấn đề này.'),
(9, 'User', 'Cảm ơn bạn rất nhiều.');

SELECT * FROM DialogList;
SELECT * FROM Users;
SELECT * FROM Dialogs;
